-- prisma/migrations/0001_initial_schema.sql
-- Auto-generated by: prisma migrate dev --name initial_schema
-- Run in production with: prisma migrate deploy

-- ─────────────────────────────────────────────────────────────────────────────
-- ENUMS
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS `users` (
  `id`               VARCHAR(191) NOT NULL,
  `email`            VARCHAR(191) NOT NULL,
  `emailVerifiedAt`  DATETIME(3)  NULL,
  `hashedPassword`   VARCHAR(191) NOT NULL,
  `name`             VARCHAR(191) NOT NULL,
  `avatarUrl`        VARCHAR(191) NULL,
  `role`             ENUM('ADMIN','USER') NOT NULL DEFAULT 'USER',
  `status`           ENUM('ACTIVE','SUSPENDED','PENDING_VERIFICATION') NOT NULL DEFAULT 'PENDING_VERIFICATION',
  `lastLoginAt`      DATETIME(3)  NULL,
  `createdAt`        DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt`        DATETIME(3)  NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_key` (`email`),
  INDEX `users_email_idx` (`email`),
  INDEX `users_status_idx` (`status`),
  INDEX `users_role_idx` (`role`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS `sessions` (
  `id`           VARCHAR(191) NOT NULL,
  `userId`       VARCHAR(191) NOT NULL,
  `sessionToken` VARCHAR(191) NOT NULL,
  `expires`      DATETIME(3)  NOT NULL,
  `createdAt`    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`),
  UNIQUE KEY `sessions_sessionToken_key` (`sessionToken`),
  INDEX `sessions_userId_idx` (`userId`),
  INDEX `sessions_sessionToken_idx` (`sessionToken`),
  CONSTRAINT `sessions_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS `categories` (
  `id`          VARCHAR(191) NOT NULL,
  `name`        VARCHAR(191) NOT NULL,
  `slug`        VARCHAR(191) NOT NULL,
  `description` TEXT         NULL,
  `iconName`    VARCHAR(191) NULL,
  `sortOrder`   INT          NOT NULL DEFAULT 0,
  `isActive`    BOOLEAN      NOT NULL DEFAULT true,
  `createdAt`   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt`   DATETIME(3)  NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE KEY `categories_name_key` (`name`),
  UNIQUE KEY `categories_slug_key` (`slug`),
  INDEX `categories_slug_idx` (`slug`),
  INDEX `categories_isActive_idx` (`isActive`),
  INDEX `categories_sortOrder_idx` (`sortOrder`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS `templates` (
  `id`               VARCHAR(191) NOT NULL,
  `categoryId`       VARCHAR(191) NOT NULL,
  `codeIdentifier`   VARCHAR(191) NOT NULL,
  `name`             VARCHAR(191) NOT NULL,
  `description`      TEXT         NULL,
  `thumbnailUrl`     VARCHAR(191) NOT NULL,
  `previewUrl`       VARCHAR(191) NULL,
  `accentColor`      VARCHAR(191) NULL,
  `isPremium`        BOOLEAN      NOT NULL DEFAULT false,
  `isActive`         BOOLEAN      NOT NULL DEFAULT true,
  `sortOrder`        INT          NOT NULL DEFAULT 0,
  `createdAt`        DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt`        DATETIME(3)  NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE KEY `templates_codeIdentifier_key` (`codeIdentifier`),
  INDEX `templates_categoryId_idx` (`categoryId`),
  INDEX `templates_codeIdentifier_idx` (`codeIdentifier`),
  INDEX `templates_isActive_idx` (`isActive`),
  INDEX `templates_sortOrder_idx` (`sortOrder`),
  CONSTRAINT `templates_categoryId_fkey` FOREIGN KEY (`categoryId`) REFERENCES `categories` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS `user_profiles` (
  `id`              VARCHAR(191) NOT NULL,
  `userId`          VARCHAR(191) NOT NULL,
  `categoryId`      VARCHAR(191) NOT NULL,
  `templateId`      VARCHAR(191) NOT NULL,
  `templateLocked`  BOOLEAN      NOT NULL DEFAULT false,
  `slug`            VARCHAR(191) NOT NULL,
  `isPublished`     BOOLEAN      NOT NULL DEFAULT false,
  `viewCount`       BIGINT       NOT NULL DEFAULT 0,
  `dynamicJsonData` JSON         NOT NULL,
  `metaTitle`       VARCHAR(160) NULL,
  `metaDescription` VARCHAR(320) NULL,
  `ogImageUrl`      VARCHAR(191) NULL,
  `createdAt`       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt`       DATETIME(3)  NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE KEY `user_profiles_slug_key` (`slug`),
  UNIQUE KEY `user_profiles_userId_categoryId_key` (`userId`, `categoryId`),
  INDEX `user_profiles_slug_idx` (`slug`),
  INDEX `user_profiles_userId_idx` (`userId`),
  INDEX `user_profiles_categoryId_idx` (`categoryId`),
  INDEX `user_profiles_templateId_idx` (`templateId`),
  INDEX `user_profiles_isPublished_idx` (`isPublished`),
  INDEX `user_profiles_createdAt_idx` (`createdAt`),
  CONSTRAINT `user_profiles_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `user_profiles_categoryId_fkey` FOREIGN KEY (`categoryId`) REFERENCES `categories` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `user_profiles_templateId_fkey` FOREIGN KEY (`templateId`) REFERENCES `templates` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
